# Python resmi imajı
FROM python:3.10-slim

# Gerekli sistem kütüphaneleri
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    libjpeg-dev \
    zlib1g-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

# Çalışma dizini
WORKDIR /app

# Proje dosyalarını kopyala
COPY . .

# Gereksinimleri yükle
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m nltk.downloader punkt stopwords vader_lexicon

# Jupyter Notebook'u başlat
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--NotebookApp.token=", "--NotebookApp.password="]
